id: ID7AAB913
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T12:49:02+00:00'
last_modified: '2022-06-07T18:23:54.651857+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W8LS16769
  title: གཏན་ཚིགས་ཐིགས་པའི་རིགས་པ་སྨྲ་བའི་མདོ་འགྲེལ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    AE26:
      image_group_id: I8LS16786
      title: ''
      total_pages: 122
      order: 1
      base_file: AE26.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
